### ISSUE TITLE
Slots are a pixel too low

### ISSUE THREAD

**Issue by ProfessorProspector** [zerofall/EZStorage2#2]
As you can see in this image, the slot appears to be selected even though there is no tooltip and you cannot take items out. http://i.imgur.com/13ljboP.png

And here, the bottom slot appears to be selected, when actually it displays the tooltip and you can take items out from the slot above: http://i.imgur.com/g0DhYdO.png

**Comment by sblectric** [comment]
I'll give this a look.

**Comment by sblectric** [comment]
Seems to be a bit more complicated to fix that I anticipated. At any rate, I will fix it eventually (if it's possible).

**Comment by ProfessorProspector** [comment]
Is it more than a simple variable being 1 too many,

**Comment by sblectric** [comment]
Yeah, it seems to be related to the mouse's actual pixel position rather than the GUI position, which is strange.

**Comment by sblectric** [comment]
Turns out, it was a GUI offset glitch, and also made the slots a pixel too far right. Fixed for next release.
