### ISSUE TITLE
Problem recovering systems.

### ISSUE THREAD

**Issue by sherkas** [zerofall/EZStorage2#21]
In the case of where player data was wiped, there should be a method to recover the items.

As it stands we now have a system unbreakable and unusable in the world. I recommend when someone has gamemode 1 and using the key they should be able to fully reset and have permissions on the system.

There was 3 of us playing a world and one user lost his data. Apon resetting there is no way to get that system working again as he was the only one with access with the security block.

**Comment by sblectric** [comment]
You can use something like MCEdit to edit the security block's TE data for now, but I'm thinking that I'll make it so players with both op permissions and creative mode can break the block in case of events like this.

**Comment by sblectric** [comment]
Added in 2.1.6.
