### ISSUE TITLE
Duplication Bug & Output Port and Double Chests

### ISSUE THREAD

**Issue by XxMiltenXx** [zerofall/EZStorage2#23]
Hello.

Versions used:
MC: 1.10.2
Forge: 12.18.0.2008
EZStorage: 2.1.6

While testing Code Chicken Chunks Ender Chests, I came across a duplication bug regarding EZStorage, which can also be reproduced with a normal (double) chest.
How it works (for easier understanding, check the attachment):
Make 2 EZStorage Systems
System 1: Storage Core, Hyper Storage Box, Access Terminal, Output Port (the output port will be put at at the end of these instructions)
System 2: Input Port, Storage Core, Hyper Storage Box, Access Terminal
Connect a Hopper to the Input Port of the 2nd System. On top of the Hopper, make a double chest towards the left. Now put more than 1728 items of the same type (I used coal) into System 1 (in my Example I put 1792).
Now place the Output below the other side of the Chest, so it pushes the items into it. The items will be pushed in, however - even thoguh it is a double chest - only 1728 (1 chest kind of). The hopper pulls the coal out of the chest into System 2. But even though it does that, 64 (1792 - 1728 = 64) items will now forever remain in System 1, and will also be continuously pushed into the chest, and will never deplete. Making you able to duplicate it.

![image](https://cloud.githubusercontent.com/assets/13734214/17034557/7bb66b52-4f83-11e6-9f8e-c7c63cb38674.png)

PS: Once you re-open the world, the bug is fixed, the item in System 1 will now deplete, however, the Output Port still only recognizes only half of the chest, so there seems to be a 2nd issue with the Output Ports and Double Chests.

**Comment by sblectric** [comment]
I am in the process of fixing and updating I/O functionality, so I will probably try to fix it for 2.2.0.

**Comment by sblectric** [comment]
OK, so far the dupe bug and general weirdness with the output port (now called the ejection port, since I am adding a less crazy output port that can have hoppers and pipes take from it) is fixed. The double chests seem to be a bug related to vanilla behavior, so I don't know if I can remedy that.

**Comment by XxMiltenXx** [comment]
Good to hear, keep it up, I really like the mod (before I used Applied Energistics, but the changes they made to 1.7.10 are not to my liking.

Btw: Is there any "proper" place where I can make feature requests for your mod?

**Comment by sblectric** [comment]
Here in the issues would be the best place.

**Comment by sblectric** [comment]
Fixed in 2.2.0.
