### ISSUE TITLE
Incompatibilities with Forge 2092

### ISSUE THREAD

**Issue by dhalek** [zerofall/EZStorage2#35]
After upgrading to to Forge-1.10.2-12.18.1.2092 getting items out of the storage does not work as expected. I tried to get 2 carbon dust from Base Metals but after clsing the UI and opening it again I have some flowers or different items in my inventory. Getting normal ores does still work but not dusts or powders.
Reverting to Forge 2088 resolved that issue.

**Comment by sblectric** [comment]
This could be #33.

**Comment by dhalek** [comment]
Maybe, but I still got the wrong items after a restart and it's singleplayer. I'll check on another computer to exclude low memory issues.

**Comment by dhalek** [comment]
So I could not reproduce this issue on another computer with more memory. I think it was just some memory issue.
