### ISSUE TITLE
Extraction Port Whitelist doesn't play nice [2.2.3]

### ISSUE THREAD

**Issue by steuff** [zerofall/EZStorage2#39]
I set up the Extraction port with a whitelist, and connected an Ender IO Item Conduit to it. The first item in the whitelist (from the left) gets pulled out of the system and into the connected machine/chest/inventory.
Now here's the issue: The Extraction port does not supply the next whitelisted item before the EZ storage system is completely emptied of the first whitelisted item. This became apparent when attempting to use a machine that autocrafts items, and takes only one stack of each item; only the first item stack got filled.

**Comment by sblectric** [comment]
The way the extraction port currently works is by a first-come-first-serve basis, not a round robin mode like you seem to want. I'll probably add a round-robin mode at some point soon.

**Comment by sblectric** [comment]
Implementation planned for 2.3.0

**Comment by sblectric** [comment]
Added in 2.3.0.
