### ISSUE TITLE
abit of wierdness as other mods update regarding ezstorage2

### ISSUE THREAD

**Issue by SDUBZ** [zerofall/EZStorage2#47]
1:just noticed the other day that shifting clicking recipes are not working properly lately O_O
2:with newer enderio and extra utilities the input does not wanna accept items from conduits and  transfer pipes the only work around was to put a hopper in between them to make them input items into the input port as shown in pic 
![2016-12-13_10 57 41](https://cloud.githubusercontent.com/assets/14084377/21121974/8c530cc4-c123-11e6-9900-f6f0c4e455c2.png)

forge: 1.10.2-2185
enderio: 1.10.2-3.0.1.139_beta
ender core: 1.10.2-0.4.1.61-beta
exu2: extrautils2-1.10.2-1.1.2
jei: jei_1.10.2-3.13.6.389

**Comment by sblectric** [comment]
What version of ez?

**Comment by SDUBZ** [comment]
oh oops its ezstorage-2.2.6

**Comment by sblectric** [comment]
OK, closing this as a duplicate. I'll have #46 fixed relatively soon.
