### ISSUE TITLE
enderio item conduits seem to not want to play nice with extraction ports.

### ISSUE THREAD

**Issue by Rensik** [zerofall/EZStorage2#49]
I can't get item conduits to extract from extraction ports - EZ2 build 2.2.6

**Comment by sblectric** [comment]
I've used these in combination without problem. Does this still happen?

**Comment by sblectric** [comment]
Well, I completely changed extraction port logic so everything should be good for the next release

**Comment by sblectric** [comment]
Fixed in 2.3.0.
