### ISSUE TITLE
Ticking issue

### ISSUE THREAD

**Issue by CamaroKing59** [zerofall/EZStorage2#53]
https://pastebin.com/dKVg1RaK

Server keeps crashing due to ticking issue

**Comment by sblectric** [comment]
Could you describe how to recreate the crash conditions?

**Comment by CamaroKing59** [comment]
basically the extractor block was placed in the world its causes a ticking loop the server eventually stops the ticking loop and runs long enough to break the block but once the block is load for a min or 2 it crashes and starts the ticking loop again so i removed the block from the world and removed the crafting recipe until it is fixed i dk it didnt start happening until i updated to the latest version

**Comment by sblectric** [comment]
This only happens if you place an extractor without it being connected to any valid system, but it will be fixed in the next versions.

**Comment by sblectric** [comment]
Fixed in 2.3.2 and 2.4.1.
