### ISSUE TITLE
Repo outdated

### ISSUE THREAD

**Issue by ptrxyz** [zerofall/EZStorage2#58]
Could you please push the latest version to GitHub? It seems that the uploaded version is a bit outdated (2.3.0). Would be great since I'd like to change some recipe for my single-player world :)

**Comment by sblectric** [comment]
you could always use [CraftTweaker ](https://minecraft.curseforge.com/projects/crafttweaker) instead of modifying and rebuilding, but yeah I will update it soon

**Comment by sblectric** [comment]
sorry, I meant Soon™ not soon

**Comment by sblectric** [comment]
Everything is now up-to-date :)

**Comment by ptrxyz** [comment]
Great, thanks a lot! :)
